const TYPES=[{code:'SICK',name:'ลาป่วย',annual:30,color:'#ef4444'},{code:'PERSONAL',name:'ลากิจ',annual:10,color:'#f59e0b'},{code:'VACATION',name:'ลาพักร้อน',annual:10,color:'#ec4899'},{code:'ANNUAL',name:'ลาเหตุประจำปี',annual:15,color:'#10b981'}];
const EMP=[{id:'EMP001',name:'ผู้ดูแลระบบ',department:'HR',role:'admin',lineUserId:'-'},{id:'EMP002',name:'หัวหน้าแผนกตัวอย่าง',department:'ฝ่ายปกครอง',role:'supervisor',lineUserId:'Uxxxx01'},{id:'EMP003',name:'พนักงานตัวอย่าง',department:'ฝ่ายปกครอง',role:'employee',lineUserId:''},{id:'EMP004',name:'HR ตัวอย่าง',department:'HR',role:'hr',lineUserId:'Uxxxx03'}];
const MONTHS=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
let state={page:'dashboard',month:new Date(),employees:load('employees',EMP),requests:load('requests',seed()),settings:load('settings',{approvalLevels:2})};
function load(k,d){try{return JSON.parse(localStorage.getItem('leave_'+k))||d}catch(e){return d}}
function save(k,v){localStorage.setItem('leave_'+k,JSON.stringify(v))}
function seed(){let now=new Date(),ym=now.toISOString().slice(0,8);return[{id:'LV-'+Date.now(),employeeId:'EMP003',employeeName:'พนักงานตัวอย่าง',department:'ฝ่ายปกครอง',leaveType:'ลากิจ',durationType:'เต็มวัน',startDate:ym+'22',endDate:ym+'22',days:1,reason:'ธุระจำเป็น',status:'PENDING',createdAt:new Date().toISOString()}]}
function $(q){return document.querySelector(q)}function $all(q){return [...document.querySelectorAll(q)]}
function toast(t){let el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function show(page){state.page=page;$all('.page').forEach(x=>x.classList.remove('active'));$('#page-'+page)?.classList.add('active');$all('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));let title={dashboard:'แดชบอร์ด',request:'ยื่นใบลา',approvals:'คิวอนุมัติ',calendar:'ปฏิทินการลา',employees:'พนักงาน',reports:'รายงาน',settings:'ตั้งค่า',guide:'คู่มือ'}[page]||page;$('#pageTitle').textContent=title;$('#pageSubtitle').textContent= page==='dashboard'?'ภาพรวมการทำงานวันนี้':'ระบบลาออนไลน์ผ่าน LINE';render()}
function statusText(s){return {PENDING:'รออนุมัติ',APPROVED_L1:'ผ่านระดับ 1',APPROVED:'อนุมัติ',REJECTED:'ไม่อนุมัติ',CANCELLED:'ยกเลิก'}[s]||s}
function statusClass(s){return {PENDING:'pending',APPROVED_L1:'level1',APPROVED:'approved',REJECTED:'rejected',CANCELLED:'cancelled'}[s]||'pending'}
function typeColor(name){return (TYPES.find(t=>t.name===name)||TYPES[0]).color}
function render(){renderStats();renderRecent();renderApprovals();renderCalendar();renderEmployees();renderReports();fillSelects();$('#pendingBadge').textContent=state.requests.filter(r=>r.status==='PENDING'||r.status==='APPROVED_L1').length}
function renderStats(){let today=new Date().toISOString().slice(0,10),m=today.slice(0,7);$('#statPending').textContent=state.requests.filter(r=>r.status==='PENDING'||r.status==='APPROVED_L1').length;$('#statToday').textContent=state.requests.filter(r=>r.startDate<=today&&r.endDate>=today&&r.status!=='REJECTED').length;$('#statMonth').textContent=state.requests.filter(r=>(r.startDate||'').startsWith(m)).length;$('#statEmployees').textContent=state.employees.length;renderChart()}
function renderChart(){let legend=$('#legendList');if(legend){legend.innerHTML=TYPES.map(t=>`<li><i style="background:${t.color}"></i>${t.name}</li>`).join('')}let bar=$('#barChart');if(bar){let nums=[2,5,3,8,4,10,3,6,2,4,7,3];bar.innerHTML=nums.map((n,i)=>`<div class="bar" style="height:${n*18}px"><span>${i+1}</span></div>`).join('')}}
function renderRecent(){let tb=$('#recentTable');if(!tb)return;tb.innerHTML=state.requests.slice().reverse().slice(0,8).map(r=>`<tr><td>${r.startDate}</td><td>${r.employeeName}</td><td>${r.leaveType}</td><td>${r.days}</td><td><span class="status ${statusClass(r.status)}">${statusText(r.status)}</span></td></tr>`).join('')||'<tr><td colspan="5">ยังไม่มีรายการ</td></tr>'}
function renderApprovals(){let box=$('#approvalList');if(!box)return;let list=state.requests.filter(r=>r.status==='PENDING'||r.status==='APPROVED_L1');box.innerHTML=list.map(r=>`<div class="approval-card"><div><b>${r.employeeName}</b> — ${r.leaveType}<br><small>${r.startDate} ถึง ${r.endDate} • ${r.days} วัน • ${r.reason||'-'}</small><br><span class="status ${statusClass(r.status)}">${statusText(r.status)}</span></div><div class="approval-actions"><button class="ghost" onclick="reject('${r.id}')">ไม่อนุมัติ</button><button class="primary" onclick="approve('${r.id}')">อนุมัติ</button></div></div>`).join('')||'<p>ไม่มีรายการรออนุมัติ เย็นกายสบายใจ</p>'}
function approve(id){let r=state.requests.find(x=>x.id===id);if(!r)return;if(state.settings.approvalLevels==2&&r.status==='PENDING')r.status='APPROVED_L1';else r.status='APPROVED';r.updatedAt=new Date().toISOString();save('requests',state.requests);toast('บันทึกอนุมัติแล้ว');render()}
function reject(id){let r=state.requests.find(x=>x.id===id);if(!r)return;r.status='REJECTED';r.updatedAt=new Date().toISOString();save('requests',state.requests);toast('บันทึกไม่อนุมัติแล้ว');render()}
window.approve=approve;window.reject=reject;
function renderCalendar(){let grid=$('#calendarGrid');if(!grid)return;let d=new Date(state.month.getFullYear(),state.month.getMonth(),1),last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();$('#monthTitle').textContent=MONTHS[d.getMonth()]+' '+(d.getFullYear()+543);let html='';for(let i=1;i<=last;i++){let ds=new Date(d.getFullYear(),d.getMonth(),i).toISOString().slice(0,10);let ev=state.requests.filter(r=>r.startDate<=ds&&r.endDate>=ds&&r.status!=='REJECTED');html+=`<div class="day"><strong>${i}</strong>${ev.map(e=>`<div class="event">${e.employeeName} ${e.leaveType}</div>`).join('')}</div>`}grid.innerHTML=html}
function renderEmployees(){let tb=$('#employeesTable');if(!tb)return;tb.innerHTML=state.employees.map(e=>`<tr><td>${e.id}</td><td>${e.name}</td><td>${e.department}</td><td>${e.role}</td><td>${e.role}</td><td>${e.lineUserId?'ผูกแล้ว':'ยังไม่ผูก'}</td></tr>`).join('')}
function renderReports(){let g=$('#reportGrid');if(!g)return;g.innerHTML=state.employees.map(e=>{let used=state.requests.filter(r=>r.employeeId===e.id&&r.status==='APPROVED').reduce((s,r)=>s+Number(r.days||0),0);let pending=state.requests.filter(r=>r.employeeId===e.id&&(r.status==='PENDING'||r.status==='APPROVED_L1')).reduce((s,r)=>s+Number(r.days||0),0);return `<div class="report-card"><b>${e.name}</b><p>${e.department}</p><p>ใช้แล้ว ${used} วัน / รออนุมัติ ${pending} วัน</p></div>`}).join('')}
function fillSelects(){let es=$('#employeeSelect'),ts=$('#leaveTypeSelect');if(es&&!es.dataset.done){es.innerHTML=state.employees.map(e=>`<option value="${e.id}">${e.id} — ${e.name}</option>`).join('');es.dataset.done=1}if(ts&&!ts.dataset.done){ts.innerHTML=TYPES.map(t=>`<option>${t.name}</option>`).join('');ts.dataset.done=1}}
$('#leaveForm')?.addEventListener('submit',e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target).entries()),emp=state.employees.find(x=>x.id===f.employeeId)||state.employees[0];state.requests.push({id:'LV-'+Date.now(),employeeId:emp.id,employeeName:emp.name,department:emp.department,leaveType:f.leaveType,durationType:f.durationType,startDate:f.startDate,endDate:f.endDate,days:Number(f.days||1),reason:f.reason,contactName:f.contactName,contactPhone:f.contactPhone,status:'PENDING',createdAt:new Date().toISOString()});save('requests',state.requests);toast('ยื่นใบลาแล้ว');e.target.reset();show('dashboard')});
$('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();state.settings=Object.fromEntries(new FormData(e.target).entries());save('settings',state.settings);toast('บันทึกการตั้งค่าแล้ว')});
$('#addEmployeeBtn')?.addEventListener('click',()=>{let n=state.employees.length+1;state.employees.push({id:'EMP00'+n,name:'พนักงานใหม่ '+n,department:'ฝ่ายปกครอง',role:'employee',lineUserId:''});save('employees',state.employees);render();toast('เพิ่มพนักงานตัวอย่างแล้ว')});
$('#exportCsvBtn')?.addEventListener('click',()=>{let rows=[['id','employee','type','start','end','days','status'],...state.requests.map(r=>[r.id,r.employeeName,r.leaveType,r.startDate,r.endDate,r.days,r.status])];let csv=rows.map(r=>r.join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='leave-report.csv';a.click()});
$('#prevMonth')?.addEventListener('click',()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()});$('#nextMonth')?.addEventListener('click',()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()});
$all('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.page));$all('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$all('.tab').forEach(b=>b.onclick=()=>{$all('.tab').forEach(x=>x.classList.remove('active'));$all('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab)?.classList.add('active')});$('#menuBtn')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
async function bootLiff(){let c=window.LEAVE_SYSTEM_CONFIG||{};if(!c.liffId)return;try{await liff.init({liffId:c.liffId});if(liff.isLoggedIn()){let p=await liff.getProfile();$('#userName').textContent=p.displayName;$('#helloName').textContent=p.displayName;$('#connectionText').textContent='LIFF Connected'}}catch(e){console.warn(e)}}
fillSelects();render();bootLiff();
